# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlRGFkS6gno3oREWxtZwwS7fuehuZm7n
"""

def greet(name):
  print("hello,"+name)
def sara():
  print("you are")