# -*- coding: utf-8 -*-
"""vijay.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaA8fLXbAEPXdXmR9veBiXXsJONJ38id
"""

def vikas():
  print("hello")
  def age():
    print("23")